Repository plone/bobtemplates.plone, pull requests merged in 2019-08, with the labels that each got.

#400 fix flake8 isort error after generation
  CHANGES.rst
  bobtemplates/plone/addon/src/+package.namespace+/+package.name+/tests/test_setup.py.bob
Labels: 01 type: bug, 14 prio: low, 23 status: testing

#401 Fix failing ./bin/update-locales if a theme is in development
  CHANGES.rst
  bobtemplates/plone/addon/src/+package.namespace+/+package.name+/locales/update.py.bob
Labels: 01 type: bug, 13 prio: normal, 23 status: testing

#404 Mr tango/template improvements
  CHANGES.rst
  bobtemplates/plone/view.py
  bobtemplates/plone/view/.mrbob.ini
  package_tests/base.py
  package_tests/test_theme.py
  package_tests/test_theme_barceloneta.py
  package_tests/test_view.py
  package_tests/test_viewlet.py
  setup.py
Labels: 04 type: enhancement
